### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by adilapapaya** [kwstat/pals#13]
Hi, thank you for this library - it looks extremely useful!

I had a question regarding the license – the repo mentions two different licenses:

- MIT in https://github.com/kwstat/pals/blob/main/LICENSE.md
- GPL-3 on the website (https://kwstat.github.io/pals/index.html) and in [LICENSE.note](https://github.com/kwstat/pals/blob/main/LICENSE.note) (where it says "The 'pals' package as a whole is released under the GPL-3 license".)

Can you help clarify if this package is released under the MIT or GPL-3 License? (We are highly discouraged from using GPL-3 licenses at work and I am trying to understand if the `pals` package is something I will be able to use or otherwise.)

Thank you again for all your work here!

**Comment by kwstat** [comment]
Thanks. I changed the license from GPL3 to MIT a year ago and just missed changing it in one spot.  Fixed.  Will try to submit a new version to CRAN, but you can install from GitHub in the meantime.

**Comment by adilapapaya** [comment]
amazing, thank you so much!!
