### ISSUE TITLE
Value-Suppressing Uncertainty Palettes

### ISSUE THREAD

**Issue by rnuske** [kwstat/pals#2]
Maybe the [Value-Suppressing Uncertainty Palettes](http://idl.cs.washington.edu/papers/uncertainty-palettes) could be a worthwhile addition ([Github Repo](https://github.com/uwdata/papers-vsup/)).

As far as i understood (I am not related to the  UW Interactive Data Lab), the Uncertainty Palette is kind of an enhanced bivariate palette for the use case of communicating uncertainty along with a value. Should be great for mapping (in the meaning of cartography) of statistics.

**Comment by kwstat** [comment]
Added vsup.redblue and vsup.viridis in https://github.com/kwstat/pals/commit/6c86056c732ce90ec4d295a08cb64e2340c34519

**Comment by rnuske** [comment]
Amazed by your speed.
Thanks a lot!
