### ISSUE TITLE
How to implement a pals palette in ggplot2 (categorical)

### ISSUE THREAD

**Issue by FelipeCarrillo** [kwstat/pals#3]
Hi;
I ran into your package and it looks like it has some features that I can use for some of my graphics. I need to include multiple colors on a graphic created with discrete data. How can I use one of your palettes inside the ggplot call? Consider the code below:
ggplot(mtcars) + 
  geom_bar(aes(factor(hp), fill=factor(hp))) +
  scale_fill_brewer(palette="polychrome")
I would like to use either polychrome, Kelly or stepped.
I saw your example with continuous data here: https://cran.r-project.org/web/packages/pals/vignettes/pals_examples.html
but my example is with categorical data. Is it possible to use your palettes here?

**Comment by kwstat** [comment]
Good question. This turned out to be harder than it could have been due to some peculiarities with ggplot2 features.  The syntax is unforgiving in multiple ways. Most difficult of all to diagnose is that the color vector CANNOT have names, hence the need for `as.vector()` to strip off the names from the polychrome colors.  This should work:

```
library(pals)
library(ggplot2)
ggplot(mtcars) + 
  geom_bar(aes(x=factor(hp), fill=factor(hp))) +
  scale_fill_manual(values=as.vector(polychrome(26)))
```
Other types of geoms might need different syntax.

**Comment by FelipeCarrillo** [comment]
That works great, thank you. I will experiment with other geoms.

**Comment by vishnu-star** [comment]
Hi, Kevin Wright,

I hope all is well with you. I recently tested your pals' color palette for my oceanographic data. I used the palette in ggplot2 and it worked for some geom and it is not working for others. Below given is the code and here it is not working. Do you have any idea? 

gplot(melt_SST,aes(x=variable,y=Longitude))+theme_bw()+
  geom_point(aes(colour=value,size=value),alpha=0.8) + guides(size="none")+
  scale_size_continuous(range = c(0,15))+
  scale_fill_manual(values=as.vector(ocean.phase(100)))

**Comment by FelipeCarrillo** [comment]
You wrote gplot instead of ggplot?

Sent from Yahoo Mail on Android 
 
  On Fri, May 27, 2022 at 3:13 PM, ***@***.***> wrote:   


Hi, Kevin Wright,

I hope all is well with you. I recently tested your pals' color palette for my oceanographic data. I used the palette in ggplot2 and it worked for some geom and it is not working for others. Below given is the code and here it is not working. Do you have any idea?

gplot(melt_SST,aes(x=variable,y=Longitude))+theme_bw()+
geom_point(aes(colour=value,size=value),alpha=0.8) + guides(size="none")+
scale_size_continuous(range = c(0,15))+
scale_fill_manual(values=as.vector(ocean.phase(100)))

**Comment by kwstat** [comment]
Reproducible examples always help.  Does this work for you?
```
library(pals)
library(ggplot2)
ggplot(mtcars) + 
  geom_bar(aes(x=factor(hp), fill=factor(hp))) +
  scale_fill_manual(values=as.vector(ocean.phase(22)))
```

**Comment by vishnu-star** [comment]
Hi Kevin,

Thanks. it does not work for my goem_point for some reason. It only works
for geom_bar

Best, Vishnu

**Comment by kwstat** [comment]
You need to use `scale_color_manual` for points and lines:
```
library(pals)
library(ggplot2)
dat <- data.frame(x=runif(50), y=runif(50),
                  z=sample(letters,50,replace=TRUE))
ggplot(dat, aes(x,y,color=z)) +
  geom_point() +
  scale_color_manual(values=as.vector(ocean.phase(26)))
```

Again, you will get better answers (and sometimes solve your own problem) if you can supply a minimal reproducible example.
