### ISSUE TITLE
Move rgl to Suggests

### ISSUE THREAD

**Issue by kent37** [kwstat/pals#4]
Please consider moving the `rgl` package from `Imports` to `Suggests` and `require`ing it in the places where it is used.

On macOS, loading `rgl` starts X11, this is not needed at all for most common uses of `pals`.

Thanks for a very useful package!

**Comment by kwstat** [comment]
Fix via 75d3994e8acedf1015c6ad66fce3154ec2a31ffc

Please test.

**Comment by kent37** [comment]
Works for me, thanks!
