### ISSUE TITLE
50 distinctive colors by combining two combining two discrete palettes

### ISSUE THREAD

**Issue by akhst7** [kwstat/pals#8]
Hi, 

I need to create 50 visually distinctive colors and to do this, I did following;

`cols<-c(polychrome(25), alphabet2(25))`

But there are still multiple colors that are substantially  similar.  I'd really appreciate if you could suggest a better approach ? 

Thanks. 

![Rplot](https://user-images.githubusercontent.com/3075799/127197247-6445e435-503a-4938-a7a2-e231cd0f595e.png)

**Comment by kwstat** [comment]
Personally I think it is impossible.  Even 25 colors is probably too many to be distinct.  But if you must, you can try something like this:
```
library(Polychrome)
# use red,green,blue seed colors. Try others too.
p1 <- createPalette(50, seedcolors=c("#ff0000"), prefix = "NC", range = c(30, 90),
              target = c("normal", "protanope", "deuteranope", "tritanope"),
              M = 50000)
library(pals)
pal.bands(p1)
```
![colors50](https://user-images.githubusercontent.com/484260/127198871-1a4e3e18-c2e4-4749-b6f3-357f44424a5e.png)
